import { Oportunidad } from './oportunidad';

export const OPORTUNIDADES: Oportunidad[] = [
    {
        "Idrequisicion": 1,
        "Consecutivo": "0000",
        "Cargo": "OPORTUNIDAD ABIERTA",
        "Arearequisicion": "",
        "Experiencia": "0 - 1",
        "Profesion": "Aplican todos los estudios académicos",
        "Ciudadsolicitud": "Nivel Nacional",
        "Fechaingreso": null,
        "Actividades": "",
        "Fechainicio": "2018-12-31",
        "Fechafin": "2020-01-01",
        "Publicarinternet": false,
        "Publicarintranet": false,
        "Propietario": "eliana.betancourt",
        "Fechacreacion": "1900-01-01T00:00:00",
        "Usuarioactulizador": null,
        "Fechaactulizacion": null,
        "Funciones": "Aplicando a la  OPORTUNIDAD ABIERTA  su Hoja de Vida ingresara en nuestra base de datos, donde será consultada para futuros Procesos de Selección",
        "Formacion": "Aplicando a la  OPORTUNIDAD ABIERTA  su Hoja de Vida ingresara en nuestra base de datos, donde será consultada para futuros Procesos de Selección",
        "Conocimientos": "Aplicando a la  OPORTUNIDAD ABIERTA  su Hoja de Vida ingresara en nuestra base de datos, donde será consultada para futuros Procesos de Selección",
        "Otros": "Aplicando a la  OPORTUNIDAD ABIERTA  su Hoja de Vida ingresara en nuestra base de datos, donde será consultada para futuros Procesos de Selección"
    },
        {
            "Idrequisicion": 1,
            "Consecutivo": "0000",
            "Cargo": "OPORTUNIDAD ABIERTA",
            "Arearequisicion": "",
            "Experiencia": "0 - 1",
            "Profesion": "Aplican todos los estudios académicos",
            "Ciudadsolicitud": "Nivel Nacional",
            "Fechaingreso": null,
            "Actividades": "",
            "Fechainicio": "2018-12-31",
            "Fechafin": "2020-01-01",
            "Publicarinternet": false,
            "Publicarintranet": false,
            "Propietario": "eliana.betancourt",
            "Fechacreacion": "1900-01-01T00:00:00",
            "Usuarioactulizador": null,
            "Fechaactulizacion": null,
            "Funciones": "Aplicando a la  OPORTUNIDAD ABIERTA  su Hoja de Vida ingresara en nuestra base de datos, donde será consultada para futuros Procesos de Selección",
            "Formacion": "Aplicando a la  OPORTUNIDAD ABIERTA  su Hoja de Vida ingresara en nuestra base de datos, donde será consultada para futuros Procesos de Selección",
            "Conocimientos": "Aplicando a la  OPORTUNIDAD ABIERTA  su Hoja de Vida ingresara en nuestra base de datos, donde será consultada para futuros Procesos de Selección",
            "Otros": "Aplicando a la  OPORTUNIDAD ABIERTA  su Hoja de Vida ingresara en nuestra base de datos, donde será consultada para futuros Procesos de Selección"
        },
        {
            "Idrequisicion": 2,
            "Consecutivo": "0001",
            "Cargo": "Estudiantes en Práctica",
            "Arearequisicion": "",
            "Experiencia": "0 - 1",
            "Profesion": "Técnicos, Tecnólogos y/o Universitarios",
            "Ciudadsolicitud": "Medellín, Cali, Bogotá",
            "Fechaingreso": null,
            "Actividades": "",
            "Fechainicio": "2008-05-01",
            "Fechafin": "2020-01-01",
            "Publicarinternet": false,
            "Publicarintranet": false,
            "Propietario": "maria.restrepo",
            "Fechacreacion": "1900-01-01T00:00:00",
            "Usuarioactulizador": null,
            "Fechaactulizacion": null,
            "Funciones": "Proyecto de práctica según formación académica.",
            "Formacion": "En áreas afines a: Mercadeo, Ventas, Administración, Sistemas, Diseño, Arquitectura, Negocios Internacionales, Comercio exterior, Producción, Procesos e Ingeniería. ",
            "Conocimientos": "Los básicos exigidos por cada programa académico. ",
            "Otros": ""
        }
    
];